[application]

# App (Project) Name
name = "Dale & Dawson Image Converter"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "dale-img-conv"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = [
    "https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css"
]

# Javascript code file
script = [
    "https://cdn.jsdelivr.net/npm/bootstrap/dist/js/bootstrap.js"
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
